# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependences
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.9
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit Test
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.9
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64
      - run: coverage run my-unittest.py


      - name: Integration Test
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.9
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64
      - run: behave tests/Integracion

  deployDev:

      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
      environment: Development
      needs: build
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Heroku Docker Container Deploy
          # You may pin to the exact commit or the version.
          # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
          uses: mtsmachado8/heroku-deploy@v2.0.3
          with:
            # Email Linked to your Heroku Account
            email: ${{secrets.HEROKU_EMAIL}}
            # Your Heroku API Key
            api_key: ${{secrets.HEROKU_API_TOKEN}}
            # Your Heroku App Name
            app_name: ${{secrets.APP_NAME}}
  
  testApiDev:
  
      runs-on: ubuntu-latest
      
      environment: Development
      
      needs: deployDev
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        
        - name: TestDev
        # You may pin to the exact commit or the version.
        # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
          uses: matt-ball/newman-action@v0.2.4
        
          with:
            # Postman API key
            apiKey: ${{secrets.POSTMAN_API}}
            # Collection to use
            collection: tests\postman\postmancollection.json
            # Environment to use
            environment: tests\postman\environments\development.json
            #........
            iterationData: tests\calc-test-data.csv
          
  deployStaging:

      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
      environment: Staging
      needs: testApiDev
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Heroku Docker Container Deploy
          # You may pin to the exact commit or the version.
          # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
          uses: mtsmachado8/heroku-deploy@v2.0.3
          with:
            # Email Linked to your Heroku Account
            email: ${{secrets.HEROKU_EMAIL}}
            # Your Heroku API Key
            api_key: ${{secrets.HEROKU_API_TOKEN}}
            # Your Heroku App Name
            app_name: ${{secrets.APP_NAME}}
