# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deployDev:

      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
      environment: Development
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Heroku Docker Container Deploy
          # You may pin to the exact commit or the version.
          # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
          uses: mtsmachado8/heroku-deploy@v2.0.3
          with:
            # Email Linked to your Heroku Account
            email: yamilka_268465460@hotmail.com
            # Your Heroku API Key
            api_key: e76a95bc-5a2a-4528-917e-6b1845f781a9
            # Your Heroku App Name
            app_name: agile-shore-03085
  
  testApiDev:
  
      runs-on: ubuntu-latest
      
      environment: Development
      
      needs: deployDev
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        
        - name: TestDev
        # You may pin to the exact commit or the version.
        # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
          uses: matt-ball/newman-action@v0.2.4
        
          with:
            # Postman API key
            apiKey: ${{secrets.POSTMAN_API}}
            # Collection to use
            collection: tests\postman\postmancollection.json
            # Environment to use
            environment: tests\postman\environments\development.json
            #........
            iterationData: tests\calc-test-data.csv
          
  deployStaging:

      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
      environment: Staging
      needs: testApiDev
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Heroku Docker Container Deploy
          # You may pin to the exact commit or the version.
          # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
          uses: mtsmachado8/heroku-deploy@v2.0.3
          with:
            # Email Linked to your Heroku Account
            email: ${{secrets.HEROKU_EMAIL}}
            # Your Heroku API Key
            api_key: ${{secrets.HEROKU_API_TOKEN}}
            # Your Heroku App Name
            app_name: ${{secrets.APP_NAME}}

  UAT:
  
      runs-on: ubuntu-latest
      
      environment: Staging
      
      needs: deployStaging
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        
        - name: TestDev
        # You may pin to the exact commit or the version.
        # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
          uses: matt-ball/newman-action@v0.2.4
        
          with:
            # Postman API key
            apiKey: ${{secrets.POSTMAN_API}}
            # Collection to use
            collection: tests\postman\postmancollection.json
            # Environment to use
            environment: tests\postman\environments\staging.json
            #........
            iterationData: tests\calc-test-data.csv


  deployToProd:
  
      runs-on: ubuntu-latest
      
      environment: production

      needs: UAT


      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        
        - name: Deploy to Heroku
          uses: mtsmachado8/heroku-deploy@v2.0.3
        
          with:
            # Email Linked to your Heroku Account
            email: yamilka_268465460@hotmail.com
            # Your Heroku API Key
            api_key: e76a95bc-5a2a-4528-917e-6b1845f781a9
            # Your Heroku App Name
            app_name: yamilkaintec-calc-prod
